"""Block-wise latent feature model (dissertation Ch4, "Block-Wise Latent Genotypes"),
generalized past genotypes/SNPs and fit with automatic differentiation instead of the
hand-derived Newton/Taylor-expansion formulas in Eqs 4.9-4.16 and 4.19-4.23.

The idea: within a block of correlated raw features (SNPs in LD, but could be any
group of spatially/temporally nearby raw signals), replace them with one shared
continuous latent variable per individual (a block-level "denoised" summary) plus
fixed per-feature deviations, related through a Simultaneous Autoregressive (SAR)
spatial model. Downstream, hierboost.spike_slab runs on the resulting block-level
design matrix exactly as it would on raw features -- decorrelation is a
pre-processing step, not a change to the inference engine.

Two modernizations relative to the dissertation:
  1. The moment-matching hyperparameter fit (Sec 4.2: choose each block's latent-
     variable mean/bandwidth so the model reproduces observed minor allele
     frequencies and correlation structure) replaces 2nd/3rd-order Taylor
     expansions of the sigmoid with reparameterized Monte Carlo expectations
     (exact in expectation, not truncated) differentiated end-to-end via JAX --
     the same reparameterization trick used to train VAEs.
  2. The per-individual/per-block Newton updates for the latent variables and
     deviations (Sec 4.3.1, Eqs 4.19-4.23) use JAX `grad`/`hessian` instead of
     hand-derived derivatives, vectorized across individuals with `vmap`. Swapping
     the observation model (Binomial -> Bernoulli/Gaussian/Poisson) or the link
     function requires changing one small function, not re-deriving five pages of
     calculus.

Requires JAX (`pip install jax`).
"""
import numpy as np
import jax
import jax.numpy as jnp

from .blocks import block_membership_lists
from .spike_slab import fit_em, ppl as ppl_fn


def _sar_B_jax(coords, phi):
    """`coords` may be 1D (m,) or 2D (m, d) -- see hierboost.kernels.sar_weight_matrix,
    whose formula and multi-D (Euclidean-distance) generalization this mirrors exactly.
    """
    if coords.ndim == 1:
        d = jnp.abs(coords[:, None] - coords[None, :])
    else:
        d = jnp.linalg.norm(coords[:, None, :] - coords[None, :, :], axis=-1)
    B = jax.scipy.stats.norm.cdf(-d / phi[:, None]) + jax.scipy.stats.norm.cdf(-d / phi[None, :])
    return B * (1.0 - jnp.eye(coords.shape[0]))


def _ar1_B_jax(coords, phi):
    """Temporal counterpart of _sar_B_jax, for a block whose members are time-ordered
    (e.g. several lags/rolling windows of one signal) rather than spatially adjacent.
    SAR's z = Bz + eps with symmetric B says "each member blends with every nearby member";
    that is the right mechanism for undirected spatial proximity but not for time, where an
    AR(1)/OU process is generated by each step depending only on its immediate predecessor.
    Using a *directed*, one-band-below-diagonal B (decay exp(-gap/phi) over the possibly
    irregular gap to the previous member in time order) in the exact same z=Bz+eps
    mechanism turns (I-B)^-1 into the AR(1) impulse-response matrix instead of a spatial
    smoother -- same reparameterization (Eq 4.6), same Newton/moment-matching machinery,
    only the mechanism generating the block's internal correlation changes. `phi` keeps
    SAR's role and units (a correlation length); only the *order* of `coords` matters here,
    so gaps need not be evenly spaced.
    """
    order = jnp.argsort(coords)
    gaps = jnp.diff(coords[order])
    decay = jnp.exp(-gaps / phi[order][1:])
    m = coords.shape[0]
    B_sorted = jnp.zeros((m, m)).at[jnp.arange(1, m), jnp.arange(0, m - 1)].set(decay)
    rank = jnp.argsort(order)
    return B_sorted[rank[:, None], rank[None, :]]


def _structure_B_jax(structure):
    return {"sar": _sar_B_jax, "ar1": _ar1_B_jax}[structure]


def _build_block_T(m):
    """Eq. 4.6's reparameterization matrix: v = (Z-tilde, delta_0, ..., delta_{m-2}) -> z,
    with the last SNP's deviation implied by the others summing to zero."""
    if m == 1:
        return jnp.eye(1)
    T = jnp.zeros((m, m))
    T = T.at[:, 0].set(1.0)
    T = T.at[jnp.arange(m - 1), 1 + jnp.arange(m - 1)].set(1.0)
    T = T.at[m - 1, 1:].set(-1.0)
    return T


def _binomial_loglik(x, n_trials, u):
    p = jnp.clip(jax.nn.sigmoid(u), 1e-7, 1.0 - 1e-7)
    return x * jnp.log(p) + (n_trials - x) * jnp.log(1.0 - p)


def fit_block_hyperparameters(coords_block, target_maf, target_corr_abs, n_trials=2,
                               tau2=1.0, n_mc=4000, n_steps=300, lr=0.1, seed=0, init_phi=None,
                               structure="sar"):
    """Sec 4.2, modernized: fit per-feature (mu, phi) so the block reproduces observed
    minor allele frequencies and |correlation| pattern, via reparameterized-MC + autodiff
    instead of Taylor-expansion moment matching. Returns (mu, phi, final_loss).

    `structure="sar"` (default) is Chapter 4's spatial model (coords_block = physical
    positions, symmetric blending). `structure="ar1"` is the temporal counterpart
    (coords_block = time/lag order, directed one-step decay) -- see _ar1_B_jax.
    """
    B_fn = _structure_B_jax(structure)
    m = coords_block.shape[0]
    # Center before casting to float32: _sar_B_jax/_ar1_B_jax only ever use pairwise
    # differences, so this is exact (translation-invariant), not an approximation -- but
    # it matters a lot in practice. Real genomic coordinates (~1e8) are well past
    # float32's precision at that magnitude (ULP ~16 near 1.3e8), which silently collapses
    # SNPs a few bp apart onto the identical float32 value and blows up the moment-
    # matching fit into NaN; centering each block on its own minimum keeps values in a
    # range (typically 0-few-thousand within one LD block) where float32 has ample
    # precision. Confirmed empirically on real 1000 Genomes data (see project memory).
    coords_block = np.asarray(coords_block, dtype=np.float64)
    coords_j = jnp.asarray(coords_block - coords_block.min(), dtype=jnp.float32)
    target_maf_j = jnp.asarray(target_maf, dtype=jnp.float32)
    target_corr_j = jnp.asarray(target_corr_abs, dtype=jnp.float32)

    key = jax.random.PRNGKey(seed)
    z_std = jax.random.normal(key, (n_mc, m))
    iu = jnp.triu_indices(m, k=1)

    maf_clipped = jnp.clip(target_maf_j / n_trials, 1e-3, 1.0 - 1e-3)
    mu0 = jnp.log(maf_clipped / (1.0 - maf_clipped))
    phi0 = jnp.full(m, float(init_phi) if init_phi else 1000.0)
    params0 = jnp.concatenate([mu0, jnp.log(phi0)])

    def unpack(params):
        return params[:m], jnp.exp(params[m:])

    def loss_fn(params):
        mu, phi = unpack(params)
        B = B_fn(coords_j, phi)
        C = jnp.linalg.inv(jnp.eye(m) - B)
        z = mu[None, :] + jnp.sqrt(tau2) * z_std
        U = z @ C.T
        p_hat = jax.nn.sigmoid(U)
        x_samples = n_trials * p_hat

        maf_hat = jnp.mean(x_samples, axis=0) / n_trials
        maf_loss = jnp.mean((maf_hat - target_maf_j / n_trials) ** 2)

        xc = x_samples - x_samples.mean(axis=0, keepdims=True)
        cov = (xc.T @ xc) / n_mc
        sd = jnp.sqrt(jnp.clip(jnp.diag(cov), 1e-8, None))
        corr_abs = jnp.abs(cov / (sd[:, None] * sd[None, :] + 1e-8))
        corr_loss = jnp.mean((corr_abs[iu] - target_corr_j[iu]) ** 2) if m > 1 else 0.0

        return maf_loss + corr_loss

    grad_fn = jax.jit(jax.grad(loss_fn))
    loss_jit = jax.jit(loss_fn)

    params = params0
    mt, vt = jnp.zeros_like(params), jnp.zeros_like(params)
    b1, b2, eps = 0.9, 0.999, 1e-8
    for t in range(1, n_steps + 1):
        g = grad_fn(params)
        mt = b1 * mt + (1 - b1) * g
        vt = b2 * vt + (1 - b2) * g ** 2
        mhat, vhat = mt / (1 - b1 ** t), vt / (1 - b2 ** t)
        params = params - lr * mhat / (jnp.sqrt(vhat) + eps)

    mu, phi = unpack(params)
    return np.array(mu), np.array(phi), float(loss_jit(params))


class BlockLatentFit:
    """Fitted SAR/AR(1)/moment-matching hyperparameters for one block, exposing
    autodiff-based Newton updates for the block-wise latent Z-tilde and the shared feature
    deviations delta (replacing Eqs 4.19-4.23). `structure` must match whatever was passed
    to fit_block_hyperparameters for this block."""

    def __init__(self, coords_block, mu, phi, tau2=1.0, n_trials=2, structure="sar"):
        self.m = len(coords_block)
        self.n_trials = n_trials
        # Same centering as fit_block_hyperparameters, and for the same reason (JAX
        # defaults to float32, whose precision at real genomic coordinate magnitude
        # silently collapses nearby-but-distinct positions) -- must match that function's
        # treatment of coords_block exactly, since B here has to be the same matrix used
        # to fit phi in the first place.
        coords_block = np.asarray(coords_block, dtype=np.float64)
        coords_block = coords_block - coords_block.min()
        B = np.array(_structure_B_jax(structure)(jnp.asarray(coords_block), jnp.asarray(phi)))
        C = np.linalg.inv(np.eye(self.m) - B)
        self.T = _build_block_T(self.m)
        Tinv = jnp.linalg.inv(self.T)
        self.mu_v = Tinv @ jnp.asarray(mu, dtype=jnp.float32)
        Sigma_v = tau2 * (Tinv @ Tinv.T)
        self.Sigma_v_inv = jnp.linalg.inv(Sigma_v + 1e-6 * jnp.eye(self.m))
        self.CT = jnp.asarray(C) @ self.T  # U = CT @ v

    def u_from_v(self, v):
        return self.CT @ v

    def infer_ztilde_from_data(self, X_block, delta_b, zt_init, n_newton=8, max_step=5.0):
        """Out-of-sample counterpart of newton_update_ztilde: infers new individuals'
        block latent from their raw features alone (data_term + prior_term only, delta_b
        held at its fitted value) since prediction-time individuals have no known y to
        supply the resp_term training conditions on. This is the discrete/binomial
        analogue of factor.py's project_block_factor / state_space.py's
        filter_temporal_block_factor.

        `max_step` damps each raw Newton step -- undamped Newton on this objective can
        overshoot into a region where the Binomial log-likelihood's curvature is nearly
        flat, producing a huge step that (via the shared outer EM loop) cascades into a
        runaway feedback with the outcome regression's coefficient and diverges to NaN
        within a handful of outer iterations. Confirmed empirically on real 1000 Genomes
        data: one block's Newton update alone reached |zt|~2.4e5 after n_newton=8 steps
        with NO damping, at outer iteration 0, before the outer EM loop had done
        anything unusual -- clipping the step is the fix, not anything about gamma or
        the outer loop itself. 5.0 is generous relative to tau2=1's implied O(1) scale
        for a standardized liability score; steps this large should only occur (and be
        clipped) during early, far-from-converged iterations."""
        m = self.m

        def obj(zt, xi):
            v = jnp.concatenate([zt[None], delta_b]) if m > 1 else zt[None]
            u = self.u_from_v(v)
            data_term = jnp.sum(_binomial_loglik(xi, self.n_trials, u))
            prior_term = -0.5 * (v - self.mu_v) @ self.Sigma_v_inv @ (v - self.mu_v)
            return data_term + prior_term

        g_fn = jax.vmap(jax.grad(obj), in_axes=(0, 0))
        h_fn = jax.vmap(jax.grad(jax.grad(obj)), in_axes=(0, 0))

        zt = zt_init
        for _ in range(n_newton):
            g = g_fn(zt, X_block)
            h = h_fn(zt, X_block)
            zt = zt - jnp.clip(g / jnp.minimum(h, -1e-4), -max_step, max_step)
        return zt

    def newton_update_ztilde(self, X_block, y, eta_partial, gamma_b, delta_b, zt_init,
                              n_newton=8, max_step=5.0):
        """Per-individual Newton update of the block latent (Eq 4.18-4.20), vectorized
        over individuals via vmap; delta_b and gamma_b are held fixed.

        `max_step` damps each raw Newton step -- see infer_ztilde_from_data's docstring
        for the full mechanism this guards against (confirmed empirically: an undamped
        step here is what actually produces the runaway |zt|/gamma blowup across outer
        iterations, not the outer EM loop itself).

        KNOWN LIMITATION (found via calibration testing, 2026-08-29, not fixed here --
        see project memory for the full diagnosis): this update includes `resp_term`,
        i.e. Z-tilde is fit with direct reference to y and the current gamma_b, unlike
        factor.py's PPCA which only ever sees raw X. That makes the outer EM loop a
        genuine joint (semi-supervised) alternation between "move Z-tilde to help
        explain y" and "re-fit gamma given Z-tilde" -- confirmed to NOT be the same
        failure mode `max_step` already guards against (|Z| stays flat/bounded across
        outer iterations even while gamma diverges), and confirmed to NOT be fixable by
        tightening kappa (tested 100/5/1: causal-block coefficients stay large and
        NULL blocks start picking up large spurious coefficients too at low kappa).
        When the true block-outcome relationship is even moderately strong relative to
        n (quasi-complete separation), gamma's EM point estimate can run to a large,
        physically implausible value while `prior_term`'s (y-independent) SAR/AR1 prior
        provides too little counterweight to stop it -- observed directly: two
        simultaneous causal blocks, n=250, true gamma~0.8/-0.64 drove the fitted
        gamma to -36/+40 over 15 outer iterations, still climbing. Practical
        implications: (1) treat fitted gamma magnitudes from this pipeline with
        suspicion when the model fits the training data unusually well relative to its
        apparent complexity; (2) hierboost.joint's regularized-horseshoe full posterior
        is the intended remedy for exactly this class of degeneracy, not a smaller
        kappa here."""
        m = self.m

        def obj(zt, xi, yi, eta_p_i):
            v = jnp.concatenate([zt[None], delta_b]) if m > 1 else zt[None]
            u = self.u_from_v(v)
            data_term = jnp.sum(_binomial_loglik(xi, self.n_trials, u))
            prior_term = -0.5 * (v - self.mu_v) @ self.Sigma_v_inv @ (v - self.mu_v)
            eta = eta_p_i + zt * gamma_b
            resp_term = yi * eta - jax.nn.softplus(eta)
            return data_term + prior_term + resp_term

        g_fn = jax.vmap(jax.grad(obj), in_axes=(0, 0, 0, 0))
        h_fn = jax.vmap(jax.grad(jax.grad(obj)), in_axes=(0, 0, 0, 0))

        zt = zt_init
        for _ in range(n_newton):
            g = g_fn(zt, X_block, y, eta_partial)
            h = h_fn(zt, X_block, y, eta_partial)
            zt = zt - jnp.clip(g / jnp.minimum(h, -1e-4), -max_step, max_step)
        return zt

    def newton_update_delta(self, X_block, zt_current, delta_init, n_newton=8, max_step=5.0):
        """Population-shared Newton update of the block's feature deviations (Eq
        4.21-4.23), summed over all individuals.

        `max_step` damps each raw Newton step, same rationale/mechanism as
        newton_update_ztilde -- applied componentwise to the solved step vector."""
        m = self.m
        if m == 1:
            return delta_init

        def per_i(zt_i, xi, delta):
            v = jnp.concatenate([zt_i[None], delta])
            u = self.u_from_v(v)
            data_term = jnp.sum(_binomial_loglik(xi, self.n_trials, u))
            prior_term = -0.5 * (v - self.mu_v) @ self.Sigma_v_inv @ (v - self.mu_v)
            return data_term + prior_term

        def total_obj(delta):
            return jnp.sum(jax.vmap(per_i, in_axes=(0, 0, None))(zt_current, X_block, delta))

        grad_fn = jax.grad(total_obj)
        hess_fn = jax.hessian(total_obj)
        delta = delta_init
        for _ in range(n_newton):
            g = grad_fn(delta)
            H = hess_fn(delta)
            step = jnp.linalg.solve(H - 1e-4 * jnp.eye(m - 1), g)
            delta = delta - jnp.clip(step, -max_step, max_step)
        return delta


def fit_latent_block_model(X, y, coords, block_id, group_wr, xi0, xi1, kappa, nu, lam,
                            n_trials=2, tau2=1.0, n_outer=15, n_inner_newton=8,
                            hyper_n_steps=200, seed=0, verbose=False, structure="sar"):
    """Orchestrates the full Ch4 pipeline, generalized:
      1. Per-block moment-matching hyperparameter fit (fit_block_hyperparameters).
      2. Alternating: Newton-update every block's Z-tilde/delta (autodiff, Sec 4.3.1),
         then re-fit gamma/theta/sigma2 by calling hierboost.spike_slab.fit_em on the
         resulting block-level design matrix -- reusing the *same* generic EM engine
         used for raw-feature spike-and-slab, since Z-tilde is just another design
         matrix once estimated (Sec 4.3.2).

    `structure="sar"` (default): `coords` are physical positions and blocks share one
    latent per individual via symmetric spatial blending (Chapter 4, unmodified).
    `structure="ar1"`: `coords` are time/lag order (e.g. several lags of one signal,
    grouped into blocks by threshold_blocks_1d/threshold_blocks_graph as usual) and
    blocks share one latent per individual via a directed AR(1)/OU step -- the discrete-
    observation temporal analogue; see hierboost.state_space for the continuous one.

    Returns a dict with the final block design matrix Z (n x K, no intercept column),
    per-block BlockLatentFit objects, deviations, and the final EMResult on Z.
    """
    n, p = X.shape
    coords = np.asarray(coords, dtype=float)
    blocks = block_membership_lists(block_id)
    block_ids = sorted(blocks.keys())
    K = len(block_ids)

    fits, deltas, Z = {}, {}, np.zeros((n, K))
    for k, b in enumerate(block_ids):
        idx = blocks[b]
        Xb = X[:, idx]
        cb = coords[idx]
        maf = Xb.mean(axis=0) / n_trials
        corr = np.abs(np.nan_to_num(np.corrcoef(Xb.T), nan=0.0)) if len(idx) > 1 else np.ones((1, 1))
        mu, phi, _ = fit_block_hyperparameters(cb, maf * n_trials, corr, n_trials=n_trials,
                                                tau2=tau2, n_steps=hyper_n_steps, seed=seed + k,
                                                structure=structure)
        fit = BlockLatentFit(cb, mu, phi, tau2=tau2, n_trials=n_trials, structure=structure)
        fits[b] = fit
        deltas[b] = jnp.zeros(max(len(idx) - 1, 0))
        # cheap init for Z-tilde: standardized block mean genotype
        Z[:, k] = (Xb.mean(axis=1) - Xb.mean()) / (Xb.std() + 1e-8)

    beta = None
    sigma2 = 1.0
    for outer in range(n_outer):
        X_design = np.column_stack([np.ones(n), Z])
        res = fit_em(X_design, y, group_wr, xi0, xi1, kappa, nu, lam,
                     beta_init=beta, sigma2_init=sigma2)
        beta, sigma2 = res.beta, res.sigma2
        gamma = beta[1:]
        eta_full = X_design @ beta

        for k, b in enumerate(block_ids):
            idx = blocks[b]
            Xb = jnp.asarray(X[:, idx], dtype=jnp.float32)
            zt_current = jnp.asarray(Z[:, k], dtype=jnp.float32)
            eta_partial = jnp.asarray(eta_full - Z[:, k] * gamma[k], dtype=jnp.float32)
            fit = fits[b]

            zt_new = fit.newton_update_ztilde(Xb, jnp.asarray(y, dtype=jnp.float32), eta_partial,
                                               gamma[k], deltas[b], zt_current, n_newton=n_inner_newton)
            delta_new = fit.newton_update_delta(Xb, zt_new, deltas[b], n_newton=n_inner_newton)
            deltas[b] = delta_new
            Z[:, k] = np.array(zt_new)
            eta_full = eta_partial + Z[:, k] * gamma[k]

        if verbose:
            mu_final = jax.nn.sigmoid(X_design @ beta)
            print(f"outer {outer:3d}  PPL={ppl_fn(y, np.array(mu_final)):.3f}")

    X_design = np.column_stack([np.ones(n), Z])
    final = fit_em(X_design, y, group_wr, xi0, xi1, kappa, nu, lam, beta_init=beta, sigma2_init=sigma2)
    return dict(Z=Z, block_ids=block_ids, fits=fits, deltas=deltas, em_result=final)


def fit_latent_block_model_crossfit(X, y, coords, block_id, group_wr, xi0, xi1, kappa, nu, lam,
                                     n_trials=2, tau2=1.0, n_outer=15, n_inner_newton=8,
                                     hyper_n_steps=200, seed=0, structure="sar", n_folds=2):
    """Cross-fitted counterpart of fit_latent_block_model, fixing the coverage problem
    documented in newton_update_ztilde's docstring: since that Newton update references
    each individual's own y directly (resp_term), an individual's fitted Z-tilde and the
    gamma later multiplying it are never independent of that individual's own outcome --
    a textbook "nuisance parameter estimated on the same data used for the target
    parameter" setup, confirmed empirically (calibration_check_joint.py) to badly
    under-cover the causal block's credible interval (~55% against a 95% nominal target).

    The fix is standard sample-splitting / cross-fitting (Chernozhukov et al. 2018,
    "Double/Debiased Machine Learning" -- the general remedy for exactly this pattern):
    partition individuals into `n_folds` folds. For each fold, fit the ENTIRE nuisance
    model (hyperparameters, delta, gamma -- the full fit_latent_block_model pipeline)
    using only the OTHER folds, then compute the held-out fold's own Z-tilde via
    `infer_ztilde_from_data` -- which already only ever uses data_term (raw X) +
    prior_term, no resp_term, i.e. it was built for genuinely new/held-out individuals
    and repurposes directly here for the same "never let y touch this individual's own
    Z-tilde" property. Every individual's final Z-tilde therefore comes from a model
    that never saw that individual's own y. A single gamma refit on the FULL n
    individuals' cross-fitted Z (standard in cross-fitting: nuisance out-of-fold, target
    parameter on the full sample for efficiency) produces the returned em_result.

    `n_folds=2` (the default) is the simplest valid form of cross-fitting (plain sample
    splitting) -- deliberately not a larger K, to keep the added cost bounded (each fold
    re-runs the full n_outer-iteration EM/Newton pipeline once): n_folds=2 costs about
    3x a single fit_latent_block_model call (two half-sample fits plus one full-sample
    fit for the returned `fits`/`deltas`, used only for future out-of-sample
    prediction -- using the full sample there is fine, since it's not the same
    individuals' own y feeding back into their own Z-tilde during THIS fit).
    """
    n, p = X.shape
    coords = np.asarray(coords, dtype=float)
    blocks = block_membership_lists(block_id)
    block_ids = sorted(blocks.keys())
    K = len(block_ids)

    rng = np.random.default_rng(seed)
    fold_assignment = rng.integers(0, n_folds, size=n)

    Z_crossfit = np.zeros((n, K))
    for k_fold in range(n_folds):
        train_idx = np.where(fold_assignment != k_fold)[0]
        heldout_idx = np.where(fold_assignment == k_fold)[0]
        if len(heldout_idx) == 0 or len(train_idx) == 0:
            continue

        result_train = fit_latent_block_model(
            X[train_idx], y[train_idx], coords, block_id, group_wr, xi0, xi1, kappa, nu, lam,
            n_trials=n_trials, tau2=tau2, n_outer=n_outer, n_inner_newton=n_inner_newton,
            hyper_n_steps=hyper_n_steps, seed=seed, verbose=False, structure=structure)

        for k, b in enumerate(block_ids):
            idx = blocks[b]
            Xb_heldout = jnp.asarray(X[heldout_idx][:, idx], dtype=jnp.float32)
            fit_trained = result_train["fits"][b]
            delta_trained = result_train["deltas"][b]
            zt_init = jnp.zeros(len(heldout_idx))
            zt_heldout = fit_trained.infer_ztilde_from_data(Xb_heldout, delta_trained, zt_init,
                                                              n_newton=n_inner_newton)
            Z_crossfit[heldout_idx, k] = np.array(zt_heldout)

    X_design = np.column_stack([np.ones(n), Z_crossfit])
    final = fit_em(X_design, y, group_wr, xi0, xi1, kappa, nu, lam)

    # fits/deltas fit on the FULL sample, for future out-of-sample prediction only -- not
    # used to compute this call's own Z_crossfit/em_result, so no leakage into the
    # coverage-relevant quantities above.
    result_full = fit_latent_block_model(
        X, y, coords, block_id, group_wr, xi0, xi1, kappa, nu, lam,
        n_trials=n_trials, tau2=tau2, n_outer=n_outer, n_inner_newton=n_inner_newton,
        hyper_n_steps=hyper_n_steps, seed=seed, verbose=False, structure=structure)

    return dict(Z=Z_crossfit, block_ids=block_ids, fits=result_full["fits"],
                deltas=result_full["deltas"], em_result=final, fold_assignment=fold_assignment)
