"""Regenerate paper/sensitivity_table.tex from results_sensitivity/sensitivity_results.json
+ results/*.json (for the SuSiE distance column) -- run after
genomics_1kg_sensitivity.py to keep the paper's sensitivity table in sync, same
discipline as build_results_table.py for the main results table. Never hand-edit
sensitivity_table.tex.
"""
import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SENS_PATH = os.path.join(ROOT, "results_sensitivity", "sensitivity_results.json")
RESULTS_DIR = os.path.join(ROOT, "results")
OUT_PATH = os.path.join(HERE, "sensitivity_table.tex")

NARRATIVE_ORDER = ["lct", "slc24a5", "darc", "edar", "herc2_oca2", "abcc11",
                    "adh1b", "apol1", "fut2", "slc45a2"]
LABEL_FIX = {"DARC": "DARC/ACKR1", "HERC2_OCA2": "HERC2/OCA2"}


def setting_tag(row):
    if row["sweep"] == "kappa":
        return f"$\\kappa$={row['kappa']:g}"
    if row["sweep"] == "gap_percentile":
        return f"pct={row['gap_percentile']}"
    if row["sweep"] == "prior_p":
        return f"$p_0$={row['prior_p']:g}"
    return "default"


def build():
    with open(SENS_PATH) as f:
        rows = json.load(f)
    susie_dist = {}
    for path in glob.glob(os.path.join(RESULTS_DIR, "*.json")):
        d = json.load(open(path))
        susie_dist[d["label"]] = d["susie_full"]["dist_bp"]

    by_locus = {}
    for r in rows:
        by_locus.setdefault(r["locus"], []).append(r)

    order = sorted(by_locus, key=lambda l: NARRATIVE_ORDER.index(l.lower())
                    if l.lower() in NARRATIVE_ORDER else 999)

    lines = [
        "% AUTO-GENERATED by paper/build_sensitivity_table.py -- do not hand-edit.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\small",
        "\\caption{Default vs.\\ best-across-the-8-settings-tried hierboost, per locus.",
        "``Best dist.\\ (oracle)'' selects the setting closest to the known causal SNP",
        "-- a retrospective upper bound on localization potential, NOT a valid tuning",
        "procedure (Sec.~\\ref{sec:sensitivity}). ``Best-acc.\\ dist.'' instead selects",
        "whichever setting has the single highest CV accuracy -- the only criterion a",
        "practitioner could use without already knowing the causal SNP.}",
        "\\label{tab:sensitivity}",
        "\\begin{tabular}{lrrlrrl}",
        "\\toprule",
        "Locus & default dist. & oracle-best dist. & (setting) & best-acc.\\ dist. & (setting) & SuSiE dist. \\\\",
        "\\midrule",
    ]
    for locus in order:
        settings = by_locus[locus]
        default = [s for s in settings if s["sweep"] == "default"][0]
        best_dist = min(settings, key=lambda s: s["dist_bp"])
        best_acc = max(settings, key=lambda s: s["acc_mean"])
        label = LABEL_FIX.get(locus, locus)
        sd = susie_dist.get(locus)
        sd_str = f"{sd:.0f}bp" if sd is not None else "n/a"
        lines.append(
            f"{label} & {default['dist_bp']:.0f}bp & {best_dist['dist_bp']:.0f}bp & "
            f"{setting_tag(best_dist)} & {best_acc['dist_bp']:.0f}bp & "
            f"{setting_tag(best_acc)} & {sd_str} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT_PATH} ({len(order)} loci)")


if __name__ == "__main__":
    build()
