"""Regenerate paper/triangulation_table.tex from results_triangulation/*.json --
run after genomics_1kg_triangulation.py to keep the paper's triangulation table in
sync. Never hand-edit triangulation_table.tex. Companion to build_purity_table.py;
reports localization distance for hierboost/SuSiE/single-SNP individually vs. the
rank-average ensemble across the same ten loci.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TRI_DIR = os.path.join(ROOT, "results_triangulation")
OUT_PATH = os.path.join(HERE, "triangulation_table.tex")

NARRATIVE_ORDER = ["lct", "slc24a5", "darc", "edar", "herc2_oca2", "abcc11",
                    "adh1b", "apol1", "fut2", "slc45a2"]
LABEL_FIX = {"DARC": "DARC/ACKR1", "HERC2_OCA2": "HERC2/OCA2"}


def build():
    rows = {}
    for f in os.listdir(TRI_DIR):
        d = json.load(open(os.path.join(TRI_DIR, f)))
        rows[d["label"]] = d

    order = sorted(rows, key=lambda l: NARRATIVE_ORDER.index(l.lower())
                    if l.lower() in NARRATIVE_ORDER else 999)

    lines = [
        "% AUTO-GENERATED by paper/build_triangulation_table.py -- do not hand-edit.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\small",
        "\\caption{Localization distance (bp from the literature-established causal",
        "SNP) for each method alone vs.\\ the rank-average ensemble. Bold marks where",
        "the ensemble strictly beats every individual method on this locus.}",
        "\\label{tab:triangulation}",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "Locus & hierboost & SuSiE & single-SNP & rank-avg ensemble \\\\",
        "\\midrule",
    ]
    dists = {"hierboost": [], "susie": [], "single_snp": [], "rank_avg": []}
    for locus in order:
        d = rows[locus]
        ind = d["individual"]
        ens = d["ensemble"]["rank_avg"]
        label = LABEL_FIX.get(locus, locus)
        hb, su, sn, ra = (ind["hierboost"]["dist_bp"], ind["susie"]["dist_bp"],
                           ind["single_snp"]["dist_bp"], ens["dist_bp"])
        for k, v in zip(dists, (hb, su, sn, ra)):
            dists[k].append(v)
        beats_all = ra < min(hb, su, sn) - 1e-9
        ra_str = f"\\textbf{{{ra:.0f}}}" if beats_all else f"{ra:.0f}"
        lines.append(f"{label} & {hb:.0f} & {su:.0f} & {sn:.0f} & {ra_str} \\\\")
    means = {k: sum(v) / len(v) for k, v in dists.items()}
    lines += [
        "\\midrule",
        f"\\textbf{{Mean}} & {means['hierboost']:.0f} & {means['susie']:.0f} & "
        f"{means['single_snp']:.0f} & \\textbf{{{means['rank_avg']:.0f}}} \\\\",
        "\\bottomrule", "\\end{tabular}", "\\end{table}",
    ]

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT_PATH} ({len(order)} loci); mean dist "
          f"hb={means['hierboost']:.0f} susie={means['susie']:.0f} "
          f"snp={means['single_snp']:.0f} rank_avg={means['rank_avg']:.0f}")


if __name__ == "__main__":
    build()
