"""Regenerate paper/purity_table.tex from results_sensitivity/sensitivity_results.json --
run after genomics_1kg_sensitivity.py to keep the paper's purity-criterion table in sync.
Never hand-edit purity_table.tex. Companion to build_sensitivity_table.py; reports the
ground-truth-free "concentration" (theta_top * purity_top) tuning criterion motivated by
Sec. sensitivity's discussion of SuSiE-style purity as a next step.
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SENS_PATH = os.path.join(ROOT, "results_sensitivity", "sensitivity_results.json")
OUT_PATH = os.path.join(HERE, "purity_table.tex")

NARRATIVE_ORDER = ["lct", "slc24a5", "darc", "edar", "herc2_oca2", "abcc11",
                    "adh1b", "apol1", "fut2", "slc45a2"]
LABEL_FIX = {"DARC": "DARC/ACKR1", "HERC2_OCA2": "HERC2/OCA2"}


def build():
    with open(SENS_PATH) as f:
        rows = json.load(f)
    for r in rows:
        r["concentration"] = r["top_theta"] * r["top_purity"]

    by_locus = {}
    for r in rows:
        by_locus.setdefault(r["locus"], []).append(r)

    order = sorted(by_locus, key=lambda l: NARRATIVE_ORDER.index(l.lower())
                    if l.lower() in NARRATIVE_ORDER else 999)

    n_match_acc, n_match_conc = 0, 0
    lines = [
        "% AUTO-GENERATED by paper/build_purity_table.py -- do not hand-edit.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\small",
        "\\caption{Ground-truth-free tuning criteria compared, per locus: selecting",
        "the setting (of the same 8 as Table~\\ref{tab:sensitivity}) with the highest",
        "CV accuracy vs.\\ the highest $\\theta_{\\text{top}} \\times$ purity$_{\\text{top}}$",
        "(``concentration''), neither of which uses the causal SNP position. A match",
        "means the criterion happened to select the oracle-best setting from",
        "Table~\\ref{tab:sensitivity}.}",
        "\\label{tab:purity}",
        "\\begin{tabular}{lrlrl}",
        "\\toprule",
        "Locus & best-acc.\\ dist. & match? & best-concentration dist. & match? \\\\",
        "\\midrule",
    ]
    for locus in order:
        settings = by_locus[locus]
        oracle = min(settings, key=lambda s: s["dist_bp"])
        best_acc = max(settings, key=lambda s: s["acc_mean"])
        best_conc = max(settings, key=lambda s: s["concentration"])
        label = LABEL_FIX.get(locus, locus)
        acc_match = abs(best_acc["dist_bp"] - oracle["dist_bp"]) < 1e-6
        conc_match = abs(best_conc["dist_bp"] - oracle["dist_bp"]) < 1e-6
        n_match_acc += acc_match
        n_match_conc += conc_match
        lines.append(
            f"{label} & {best_acc['dist_bp']:.0f}bp & {'yes' if acc_match else '--'} & "
            f"{best_conc['dist_bp']:.0f}bp & {'yes' if conc_match else '--'} \\\\"
        )
    mean_acc = sum(max(by_locus[l], key=lambda s: s["acc_mean"])["dist_bp"] for l in order) / len(order)
    mean_conc = sum(max(by_locus[l], key=lambda s: s["concentration"])["dist_bp"] for l in order) / len(order)
    lines += [
        "\\midrule",
        f"\\textbf{{Mean / match count}} & {mean_acc:.0f}bp & {n_match_acc}/10 & "
        f"{mean_conc:.0f}bp & {n_match_conc}/10 \\\\",
        "\\bottomrule", "\\end{tabular}", "\\end{table}",
    ]

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {OUT_PATH} ({len(order)} loci); accuracy {n_match_acc}/10, "
          f"concentration {n_match_conc}/10 matches; mean dist acc={mean_acc:.0f}bp "
          f"conc={mean_conc:.0f}bp")


if __name__ == "__main__":
    build()
